<a href="https://colab.research.google.com/github/nikitask14/pytorch-engineering-to-federated-learning/blob/main/18_inspecting_parameters_and_gradients.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn
from torchvision import datasets

In [ ]:
class MyModel(nn.Module):
  def __init__(self):
    super().__init__()

    self.layer1 = nn.Linear(784,128)
    self.layer2 = nn.Linear(128,10)

  def forward(self, x):
    x = torch.relu(self.layer1(x))
    x = self.layer2(x)
    return x


In [ ]:
model = MyModel()
model.parameters()

for parameter in model.parameters():
  print(parameter.shape)

torch.Size([128, 784])
torch.Size([128])
torch.Size([10, 128])
torch.Size([10])


torch.Size([128, 784])   → layer1 weights


torch.Size([128])        → layer1 bias



torch.Size([10, 128])    → layer2 weights


torch.Size([10])         → layer2 biasFor layer1 = nn.Linear(784, 128):

128 neurons
each neuron has 784 incoming weights
therefore weight tensor = (128, 784)
one bias per neuron = (128,)

In [ ]:
for name, parameter in model.named_parameters():
  print(name, parameter.shape)
  print(name, parameter.grad)


layer1.weight torch.Size([128, 784])
layer1.weight None
layer1.bias torch.Size([128])
layer1.bias None
layer2.weight torch.Size([10, 128])
layer2.weight None
layer2.bias torch.Size([10])
layer2.bias None


In [ ]:
x =torch.randn(4, 784)
y = torch.tensor([0, 1, 2, 3])
print(x.shape)
print(y.shape)

torch.Size([4, 784])
torch.Size([4])


In [ ]:
loss_fn = nn.CrossEntropyLoss()
logits = model(x)
loss = loss_fn(logits, y)
print(logits.shape)
print(loss)
loss.backward()


torch.Size([4, 10])
tensor(2.1868, grad_fn=<NllLossBackward0>)


In [ ]:
for name, parameter in model.named_parameters():
  # print(name, parameter.grad)
  # print(parameter.grad.shape)
  print(name, parameter.grad.shape)

layer1.weight torch.Size([128, 784])
layer1.bias torch.Size([128])
layer2.weight torch.Size([10, 128])
layer2.bias torch.Size([10])


In [ ]:
print(model.layer2.bias.grad)
print(model.layer2.weight.grad[0, 0])

tensor([-0.1379, -0.1351, -0.1606, -0.1448,  0.1116,  0.0820,  0.1287,  0.0948,
         0.0745,  0.0868])
tensor(-0.0967)
